
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_DATABASE: audit
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  rabbitmq3:
   container_name: rabbitmq
   image: rabbitmq:3.8-management-alpine
   ports:
    #AMQP protocol port
     - 5672:5672
    #HTTP management UI
     - 15672:15672
